### ISSUE TITLE
为什么有些拼音翻译不出来，是库不全吗？

### ISSUE THREAD

**Issue by mosion** [hotoo/pinyin#107]
如 ： pinyin("深圳北",{
  style: pinyin.STYLE_TONE2
})   会输入  [["shen1"],["圳"],["bei3"]]  

还有 请教一下假如 我想对  var mockData = [{
        id: '001',
        type: "深圳南"
    }, {
        id: '002',
        type: "深圳北站"
    }, {
        id: '003',
        type: "深圳东"
    }, {
        id: '004',
        type: "神龙"
    }];

这个对象数组进行排序，希望结果是：
var mockData = [{
        id: '002',
        type: "深圳北站"
    }, {
        id: '003',
        type: "深圳东"
    }, {
        id: '001',
        type: "深圳南"
    } , {
        id: '004',
        type: "神龙"
    }];

能否提供ES5写法的思路参考或者你们可考虑是否可以把这个复杂的功能加进入

**Comment by hotoo** [comment]
duplicated #105 #98
