### ISSUE TITLE
react native bug

### ISSUE THREAD

**Issue by sym900728** [hotoo/pinyin#113]
在react native 项目中运行，其中有很多字无法转换成拼音。

**Comment by hotoo** [comment]
跟 React Native 应该没关系。请明确哪些字有问题，给出可以复现的相关代码或 Demo

**Comment by sym900728** [comment]
1. 使用 node 环境，这种情况下面是可以使用的。
![image](https://cloud.githubusercontent.com/assets/4710194/20468582/f59c5bca-afd2-11e6-9aa2-85f4eed5619f.png)

2. 在 react native 环境中。
(react native 工程的构建参考 react native 官网。)

下面是工程代码
![image](https://cloud.githubusercontent.com/assets/4710194/20468736/acc24d68-afd4-11e6-8e49-8b3acf930b97.png)

下面是调试结果
![image](https://cloud.githubusercontent.com/assets/4710194/20468745/c7dedaa8-afd4-11e6-9150-bb14c63faf09.png)

其中蔡字，拼音首字母没有被提取出来。

**Comment by hotoo** [comment]
你这使用的是 Web 版、客户端的，拼音库比较小。

对应拼音来说，还是建议在服务端使用，将汉字的拼音生成后持久化存储下来会比较好。

**Comment by sym900728** [comment]
那怎样在react native 中使用 node 版本？因为我现在需要在react native中使用。

**Comment by marlti7** [comment]
同问 @sym900728  你解决了吗？

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`，Web browser 也支持了完整的字库。
