### ISSUE TITLE
node v6.9.1 安装pinyin 报错，要怎么解决呢

### ISSUE THREAD

**Issue by chelsh** [hotoo/pinyin#115]
app-10     Segment need nodejieba, please run '$ npm install nodejieba'.
app-10     分词需要使用 nodejieba 模块，请运行 '$ npm install nodejieba' 并确保安装完成。
app-10 Error: Module version mismatch. Expected 48, got 47.
app-10     at Error (native)
app-10     at Object.Module._extensions..node (module.js:597:18)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/20829767/78dec818-b8b8-11e6-881b-5dc1f6e4456f.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/20829796/9743ed1a-b8b8-11e6-84bb-7e4c869315df.png)

**Comment by chelsh** [comment]
nodejieba 明明已经安装了

**Comment by yanyiwu** [comment]
@chelsh 你先 remove -r node_modules/nodejieba ，然后再 npm install nodejieba 看看有什么报错信息吗？有的话贴一下？因为你的 node_modules/nodejieba 可能是从别的机器上拷贝过来的，可能环境不一致。

**Comment by yanyiwu** [comment]
@chelsh  https://github.com/yanyiwu/nodejieba/pull/79 nodejieba 是支持 6.9.1  的。

**Comment by clonn** [comment]
經過自己的測試，在測試的 project 裡面， package.json 的 `name:` 名稱值，不可以和其中的 dependency module 名稱一樣，否則會造成 `npm install refuse`. 

建議修改， `package.json` 內容如下，

```
{
  "name": "nodejiebatest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "nodejieba": "^2.2.4"
  }
}
```

重新再把 `node_modules` 砍掉，再重新執行一次 `npm install` 就可以順利安裝了。
