### ISSUE TITLE
webpack构建项目时，报错了！

### ISSUE THREAD

**Issue by lie1992** [hotoo/pinyin#118]
错误如下，
ERROR in static/js/vendor.4a9ed532fd1da324b937.js from UglifyJs
SyntaxError: Unexpected token name «i», expected punc «;» [./~/pinyin/lib/pinyin
.js:34,0]

这个是在vue2框架运行编译的时候，报错的，这个该如何解决？
已经配置了babel，但是好像没有用

**Comment by hotoo** [comment]
https://github.com/hotoo/pinyin/blob/master/lib/pinyin.js#L34

我也看不懂这一行有什么错。

**Comment by wenhuix** [comment]
同样报错：
    ERROR in tab-site-issue-input-1dd4064a188fa41dcab5.js from UglifyJs
    SyntaxError: Unexpected token name «i», expected punc «;» [./~/.2.8.0@pinyin/lib/pinyin.js:34,0]

**Comment by wangqianliangM** [comment]
同样的错误, 在 webpack 打包的时候

**Comment by alonestar** [comment]
报错后chrome和火狐使用正常,但是ie会导致页面无法正常打开
先通过simple-pinyin这个库解决了拼音的问题

**Comment by adolli** [comment]
很好的库呢，但同样遇到 `Unexpected token name «i», expected punc «;» (line: 22802, col: 11, pos: 732338` 这个问题，希望作者解决，拜托。

**Comment by Wulawa** [comment]
下个es6-loader 在配置文件里 {
        test: /\.js$/,
        loader: 'babel!es6',
        include: projectRoot,
        exclude: /node_modules/
      },

**Comment by hotoo** [comment]
因为 exclude 了 node_modules，所以使用 es6 编写的 pinyin 并为被 babel 编译。

建议在 Node 中使用，并持久化转换后的拼音结果。

**Comment by adolli** [comment]
如果关掉了压缩（uglify）确实是可以build通过，但是这样代码就会变得比以前大4倍左右。尝试过把这个库exclude uglify但是不成功。
