### ISSUE TITLE
你好，关于多音字转为有带声调出错，有什么方法可以解决

### ISSUE THREAD

**Issue by dearwind153** [hotoo/pinyin#119]
你好，关于多音字转为有带声调出错，有什么方法可以解决

1. 测试用句：商贾，贾平凹同志
2. 拼音转换结果为： [ [ 'shang1' ], [ 'gu3' ], [ '，' ], [ 'gu3' ], [ 'ping2' ], [ 'ao1' ], [ 'tong2' ], [ 'zhi4' ] ]
3. 测试条件：已经开启分词
console.log(pinyin("商贾，贾平凹同志", {
  //style: pinyin.STYLE_INITIALS, // 设置拼音风格
  style: pinyin.STYLE_TONE2, // 设置拼音风格
  heteronym:false, 
  segment: true                 // 启用分词，以解决多音字问题。
}));

**Comment by hotoo** [comment]
目前使用的分词算法没有提供所分词组的词性，所以目前并没有很好的办法。
如果分词算法提供了分词词性（如普通词组、地名、人名等）就可以针对性处理。

**Comment by hotoo** [comment]
cc @yanyiwu

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`，支持姓名模式。
