### ISSUE TITLE
'迪'这个字貌似没有正常输出结果

### ISSUE THREAD

**Issue by luchenwei9266** [hotoo/pinyin#121]
![image](https://cloud.githubusercontent.com/assets/9455826/23738602/e8a53aca-04d4-11e7-8aee-4858595795f1.png)

![image](https://cloud.githubusercontent.com/assets/9455826/23738584/d726487a-04d4-11e7-839a-6c77ab5eb069.png)

**Comment by hotoo** [comment]
#111 #120
