### ISSUE TITLE
厦门分词模式

### ISSUE THREAD

**Issue by bingyiyu1** [hotoo/pinyin#122]
console.log(pinyin('厦门',{style :pinyin.STYLE_NORMAL,heteronym: true,segment: true }));
console.log(pinyin('厦门',{style :pinyin.STYLE_NORMAL }));
console.log(pinyin('重庆',{style :pinyin.STYLE_NORMAL,heteronym: true,segment: true }));
console.log(pinyin('重庆',{style :pinyin.STYLE_NORMAL }));

[ [ 'sha', 'xia' ], [ 'men' ] ]
[ [ 'sha' ], [ 'men' ] ]
[ [ 'chong' ], [ 'qing' ] ]
[ [ 'zhong' ], [ 'qing' ] ]
= = 为什么重庆的分词模式起作用了 厦字还是输出了两个拼音 很尴尬= =

**Comment by hotoo** [comment]
fixed it on v2.8.2
