### ISSUE TITLE
mocha 测试 --check-leaks不通过

### ISSUE THREAD

**Issue by bingyiyu1** [hotoo/pinyin#124]
这是mocha的test测试的设置
```
    "test": "mocha  --harmony_proxies  --reporter spec --check-leaks --globals  csvFile,l  test/*/*.test.js",
```
   npm test 运行后第一次执行pinyin(name,{style :pinyin.STYLE_NORMAL,heteronym: true,segment: true }):
 会报错     Error: global leaks detected: dict, hmmDict, userDict, idfDict, stopWordDict;
是heteronym: true引起的= =||;感觉是mocha的坑.如果能帮忙优化是极好的.
还有前两天的厦门多音字帮忙解决了谢谢@_@.这里还找到两个错的    
name = modifyPinyin('LvXingShe','旅行社',name,isFull); 会变成lvhangshe
name = modifyPinyin('XinYongKa','信用卡',name,isFull);会变成xinyongqia

发现后我手动写方法修改了.机智如我~

维护这个库~大佬辛苦了~向大佬致敬~给大佬递茶

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`
