### ISSUE TITLE
使用的require的方式引入的pinyin,有部分汉字没有转化成首字母拼音

### ISSUE THREAD

**Issue by dragonHu** [hotoo/pinyin#127]
代码如下:
 let parr=pinyin(item.substr(0,1),{
      style: pinyin.STYLE_FIRST_LETTER, // 设置拼音风格
      heteronym: true
});
 console.log(JSON.stringify(parr));
结果打印日志如下：
[["菁"]]
 [["麒"]]
 [["哇"]]
 [["臻"]]

**Comment by hotoo** [comment]
浏览器端只有常用字库。建议在服务端转换拼音并持久化。
