### ISSUE TITLE
web端用webpack UglifyJsPlugin打包，报错Unexpected token name «i», expected punc «;» [./~/pinyin/lib/pinyin.js:34,0]

### ISSUE THREAD

**Issue by Jim-MK** [hotoo/pinyin#129]
webpack配置了babel，可以把es6转成es2015
webpack配置好了UglifyJsPlugin，压缩时候报错
Unexpected token name «i», expected punc «;» [./~/pinyin/lib/pinyin.js:34,0]

ps： window环境

**Comment by hotoo** [comment]
#118 不建议在客户端使用 pinyin 库，一定要用，打包时不要排除 node_modules 目录

**Comment by hughfenghen** [comment]
解决方法：
1、按文档描述，不建议在客户端使用 pinyin 库。
2、不排除node_modules；如果去掉`exclude: /node_modules/`报错可改用`include: [...]`配置，引入src、pinyin等需要babel编译的目录。

**Comment by heihei001** [comment]
@Jim-MK 我跟你一样出错了，但是修改了一下include就行了，配置如下
resolve('node_modules/_pinyin@2.8.3@pinyin')，改成这样就行了

**Comment by qiuyaofan** [comment]
resolve('node_modules/_pinyin@2.8.3@pinyin')是在哪里改的？ @heihei001

**Comment by Shuliyey** [comment]
原因是因为 uglifyjs 不支持ES6 (ES2015), 所以你需要在webpack uglify 之前, 把错误的文件（或文件夹）用babel-loader 处理

@qiuyaofan 这个需要根据你的webpack 格式情况, 与你webpack config 的某个文件里面改， 我用Vue webpack template 打个比方

vue webpack template 有个 `build/webpack.base.conf.js` 文件

![image](https://user-images.githubusercontent.com/4773348/32254823-97b61b38-bef7-11e7-8727-8395a10983d3.png)

这文件的有这一段

```js
var path = require('path')
var utils = require('./utils')
...
module.exports = {
...
  module: {
    ...
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('node_modules/instascan/src/scanner.js'),
          resolve('node_modules/instascan/src/camera.js'),
          resolve('node_modules/pinyin'),
          resolve('test')
        ]
      },
```
这段代表的就是用 `babel-loader` 把 这些 `include` 的所有文件（和文件夹里任何文件), 用babel-loader 处理, 你会发现你的`src` 也在这个 `include` 列组里 (很容易理解，因为写Vue, 就基本会用到 ES6 syntax)

我把 
```js
          resolve('node_modules/instascan/src/scanner.js'),
          resolve('node_modules/instascan/src/camera.js'),
          resolve('node_modules/pinyin')
```
这三个都加进去了，前两个很明确的两个文件(因为我知道我打包时会用到这两个文件)有ES6 syntax, 最后一个pinyin (npm module), 我为了方便就把整个`pinyin`文件夹里，所有的js 文件都用babel-loader 处理。(其实在这个情况如果你很清楚只会用到这个`./~/pinyin/lib/pinyin.js`， 你也可以写成 `resolve('node_modules/pinyin/lib/pinyin.js')`)

主要记住一个原理就是

基本上任何与javascript syntax 有关的问题 (build 会报错是哪个文件, 而且一般都是在uglify 环节), 都可以放到这里。指定先用babel-loader 转换成最基础的javascript 格式， 这样一般后续环节都不会有javascript syntax 问题。

**Comment by Shuliyey** [comment]
@qiuyaofan , 成功用webpack 打包后， 可能你还会遇到一个新问题
```
Cannot assign to read only property 'exports' of object '#<Object>'
```
解决这问题的一个方法就在
https://github.com/webpack/webpack/issues/4039#issuecomment-283501082
把`.babelrc` 里 es version 里的 `module: false` 删掉就行

**Comment by qiuyaofan** [comment]
@Shuliyey 谢谢

**Comment by EasonYou** [comment]
@Shuliyey 把``.babelrc`` 里 es version 里的 ``module: false``  删掉后整个项目都成了``export is not defined`` 了，怎么解决。同样是vue-cli的

**Comment by Shuliyey** [comment]
@EasonYou 
上传下你的 ·.babelrc· 和 ·webpack.config·

**Comment by wang1052303865** [comment]
问题解决
1.build/webpack.base.conf.js 文件
 {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('node_modules/_pinyin@2.8.3@pinyin')
          resolve('test')
        ]
      },


2、npm install babel-plugin-transform-es2015-modules-commonjs

然后在 babelrc中配置

{ "plugins": ["transform-es2015-modules-commonjs"] }
即可解决

**Comment by wangliangyu** [comment]
各位好，我这边已经将报错的文件都加到resolve路径中了，一开始是上面assist.js报错，我加上去就好了，但是后面那个index.js加上去还一直报错。 resolve('src')和resolve('/src/index.js')都试过了，咋回事？
`     
   {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('/node_modules/iview/src/utils/assist.js'),
          resolve('src')
        ]
    }
`
报错如下，我还用了@wang1052303865所说的**babel-plugin-transform-es2015-modules-commonjs**，另外我用的是webpack-simple模板，麻烦帮看下咋回事，谢谢~
`
ERROR in build.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./src/index.js:12,0][build.js:11508,35]
`

**Comment by montilloo** [comment]
gulp-uglify-es
gulp stream to uglify with 'terser' (es6 supported).
[这个包](https://www.npmjs.com/package/gulp-uglify-es)支持es
