### ISSUE TITLE
选择首字母风格(.STYLE_FIRST_LETTER)，首字母为"o"的字不会转换成字母。

### ISSUE THREAD

**Issue by rockjins** [hotoo/pinyin#132]
```js
pinyin("哦噢我",{
    style:pinyin.STYLE_FIRST_LETTER
})
```

返回：
```js
[
    [
        "哦噢"
    ],
    [
        "w"
    ]
]
```
只有拼音为"o"的字会出现这种情况，望修复，辛苦了。

**Comment by yorts52** [comment]
我这边测试的结果是这样的, 并没有你说的这个问题:
```js
let words = '哦噢我';
console.log(pinyin(words, {
    style: pinyin.STYLE_FIRST_LETTER,
})); // [ [ 'o' ], [ 'o' ], [ 'w' ] ]

console.log(pinyin(words, {
    style: pinyin.STYLE_FIRST_LETTER,
    heteronym: true,
})); // [ [ 'o', 'e' ], [ 'o' ], [ 'w' ] ]

console.log(pinyin(words, {
    style: pinyin.STYLE_FIRST_LETTER,
    heteronym: true,
    segment: true,
})); // [ [ 'o', 'e' ], [ 'o' ], [ 'w' ] ]
```

**Comment by rockjins** [comment]
好奇怪哦，但是我这怎么 ...而且只有o开头的字会这样：
![image](https://cloud.githubusercontent.com/assets/17586155/24889118/c915f4da-1e9a-11e7-8347-a03a553af006.png)
这是打印出来的值：
![image](https://cloud.githubusercontent.com/assets/17586155/24889135/e4fece1a-1e9a-11e7-9448-7b5cf8dcefb3.png)
我也不懂为咩...

**Comment by hotoo** [comment]
Web 版的只有法定的常用字库，建议在 Node 端使用并持久化。

**Comment by mengqinWu** [comment]
pinyin("韦",{
    style:pinyin.STYLE_FIRST_LETTER
})
![image](https://user-images.githubusercontent.com/19563091/37511632-8b24f6de-293a-11e8-975a-2287ee1035f3.png)
