### ISSUE TITLE
能否提供份编译的版本，方便开发者使用

### ISSUE THREAD

**Issue by tomoyuen** [hotoo/pinyin#133]
main指向的是`lib/index.js`，一般项目配置babel-loader时，会将node_modules目录设为exclude，而通过`require('pinyin')`引入的时候，编译出来的文件还会是es6的代码，能不能提供一份编译的版本呢？

**Comment by hotoo** [comment]
不建议在 Web 端使用，建议在 Node 端使用并持久化结果。

**Comment by tomoyuen** [comment]
好吧，谢谢
