### ISSUE TITLE
关于多音字字典

### ISSUE THREAD

**Issue by suntong** [hotoo/pinyin#134]
Hi, 

关于多音字, may I know where do you get your 多音字 dictionary from?

Just picking top several from the `dict-zi.js` dictionary:

```
dict[0x3401] = "tiǎn,tiàn"; /* 㐁 */
dict[0x3406] = "yǐn,yī"; /* 㐆 */
dict[0x340c] = "sì,yí"; /* 㐌 */
dict[0x3432] = "dài,fú"; /* 㐲 */
dict[0x3437] = "mǎ,mà,mián"; /* 㐷 */
dict[0x343a] = "zhòng,yín"; /* 㐺 */
dict[0x343c] = "chèng,zhěng"; /* 㐼 */
dict[0x343e] = "ruǎn,yuàn"; /* 㐾 */
dict[0x3442] = "fǎng,páng"; /* 㑂 */
dict[0x344b] = "jiòng,kǒng,qióng"; /* 㑋 */
dict[0x344d] = "lěi,lèi"; /* 㑍 */
dict[0x3451] = "lǎn,jì"; /* 㑑 */
dict[0x3459] = "dié,yǒng"; /* 㑙 */
dict[0x345c] = "yì,chì"; /* 㑜 */
```

Are these really 多音字?

As I'm look at [Unihan_Readings.txt](https://github.com/go-cc/cc-table/blob/master/Unihan/Unihan_Readings.txt) from http://www.unicode.org/Public/UNIDATA/Unihan.zip, and I'm not seeing the above characters as 多音字. 

What I'm missing? Thanks.

**Comment by hotoo** [comment]
- http://www.zdic.net/
- http://www.zdic.net/z/e/js/3401.htm
- https://github.com/hotoo/pinyin/blob/master/tools/robot-zdic-zi.js

**Comment by suntong** [comment]
Oh, thanks a lot!
