### ISSUE TITLE
你好，能否在词库中增加三个常用字

### ISSUE THREAD

**Issue by zlh562011966** [hotoo/pinyin#136]
能否pinyin/data/dict-zi-web.js文件里加三个字：珂、柯、喽（常用字）
在汉字转为拼音时，代码如下：
pinyin(“珂柯喽”, { // 取汉字首字母
	style: pinyin.STYLE_FIRST_LETTER
});
实际结果为：珂柯喽
期望结果：KKL

非常谢谢！

**Comment by hotoo** [comment]
汉字拼音库比较大，放在客户端运行不是特别合适，所以 web 版的词库只有汉语规范定义的常用字（你上面 3 个除了 柯 看起来常用外，其他都不是常用字。

转换拼音最好还是在服务端（Node）进行，并持久化存储起来，避免客户端每次运行都要转换一次。

**Comment by jinggoing** [comment]
深圳的 圳 字也没有在字典里吗

**Comment by hotoo** [comment]
用 Node 版就没有这种困扰了

**Comment by meteorlxy** [comment]
用来做姓名检索，部分姓氏和常见的用在名字里的字都没有。是用webpack打包的node版。

人数不多，也就几十人，光姓氏就少了 闵 邵 阚 姬 虞

感觉至少可以把百家姓补全？
