### ISSUE TITLE
用webpack打包出错 

### ISSUE THREAD

**Issue by CrazyAlvaro** [hotoo/pinyin#137]
```
SyntaxError: Unexpected token name «i», expected punc «;» [./~/.2.8.3@pinyin/lib/pinyin.js:34,0]
```

已经在webpack中配置了babel-loader，但是似乎这段代码仍就没有被转换，可以帮忙看看吗？

**Comment by cmic1980** [comment]
遇到同样的错误，请问你解决了吗？

**Comment by CrazyAlvaro** [comment]
@cmic1980 嗯，参照这个[issue](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/33)的解决方案，使用harmony版本，然后在webpack配置文件中使用。

**Comment by hotoo** [comment]
#129

**Comment by xiongmaozhanjiangshi2** [comment]
在webpack.base.conf修改一下js加载那边的配置改成这样的
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/.2.8.3@pinyin')]
      },

**Comment by CrisLi** [comment]
把uglifyjs-webpack-plugin升级到v1.0.0-beta.2就能解决。

**Comment by mengqinWu** [comment]
![image](https://user-images.githubusercontent.com/19563091/33226637-b0870cf6-d1cd-11e7-8e0e-a8aeb6bbb589.png)
![image](https://user-images.githubusercontent.com/19563091/33226660-1f99485c-d1ce-11e7-9e9a-ff530fe18ef3.png)
![image](https://user-images.githubusercontent.com/19563091/33226668-36e544f2-d1ce-11e7-8df6-99891be66822.png)

打包没问题，可是运行有问题

**Comment by mmyxjx** [comment]
{
test: /.js$/,
loader: 'babel-loader',
include: [resolve('src'), resolve('test'), resolve('node_modules/.2.8.3@pinyin')]
},
resolve 是path.resolve，搞半天没发现   ，大家可注意啦

**Comment by MemoSanMu** [comment]
如果您用dva roadhog 打包⬇️
解决方案： https://github.com/sorrycc/blog/issues/68?utm_medium=hao.caibaojian.com&utm_source=hao.caibaojian.com

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`
