### ISSUE TITLE
获取拼音首字母有问题，汉字和转义的匹配不上

### ISSUE THREAD

**Issue by zero009** [hotoo/pinyin#152]
let str = pinyin('大哥', {
          style: pinyin.STYLE_FIRST_LETTER,
          heteronym: true}).join().toUpperCase().replace(/,/g, '')
 console.log( str )
获取拼音首字母，有些汉字获取的首字母不正确，比如大

**Comment by hotoo** [comment]
你传入了要求返回多音字拼音的参考，`大哥` 的拼音结果是 `[ [ 'd', 't' ], [ 'g' ] ]`。
`大` 字是多音字，有 `[ [ 'dà', 'dài', 'tài' ] ]` 三个读音。
我这边看了是正确的，不知道你说哪里不正确。
