### ISSUE TITLE
Mac安装失败

### ISSUE THREAD

**Issue by ZhongbinHuang** [hotoo/pinyin#164]
> nodejieba@2.2.5 install /Users/timo/Desktop/work/app/trunk/client/SQApp2/node_modules/nodejieba
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejieba/lib/index.o
clang: warning: using sysroot for 'iPhoneOS' but targeting 'MacOSX'
In file included from ../lib/index.cpp:1:
In file included from ../lib/nodejieba.h:4:
In file included from ../lib/utils.h:4:
In file included from /Users/timo/.node-gyp/6.9.1/include/node/node.h:42:
In file included from /Users/timo/.node-gyp/6.9.1/include/node/v8.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/stdint.h:63:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/include/sys/_types.h:32:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/include/sys/cdefs.h:761:2: error: 
      Unsupported architecture
#error Unsupported architecture

**Comment by hotoo** [comment]
@yanyiwu
