### ISSUE TITLE
默认提供babel转换版本

### ISSUE THREAD

**Issue by janryWang** [hotoo/pinyin#165]
目前package.json里依赖的lib/index.js是ES6版本，webpack打包，在压缩的时候会报错，除非去掉exclude:/node_modules/，但是会影响构建性能，除非针对pinyin进行特殊exclude，但是这会让用户很疑惑

**Comment by hotoo** [comment]
建议在服务端使用 Node 进行拼音转换后持久化，这样可以避免避免客户端每次都需要重复转换，提升性能和可用性

**Comment by janryWang** [comment]
@hotoo 这个库目前主要用于搜索过滤列表，数据量不大，转换成本也不高，但能大大提升用户体验

**Comment by hotoo** [comment]
把你的使用场景给我描述下

**Comment by janryWang** [comment]
@hotoo 目前我是有一个下拉选择列表，支持搜索列表项的，平时用户在打字的时候都是拼音开始，最后才有中文，为了优化用户体验，在拼音级别的时候也做搜索，所以这种场景下需要pinyin这个库啊

**Comment by hotoo** [comment]
你这种场景适合对这个选择的下拉列表，做拼音转换并持久化，然后用户在输入的时候你对比拼音或者中文就可以了。

**Comment by janryWang** [comment]
@hotoo 下拉列表是前端生成的，不是服务端控制的

**Comment by hotoo** [comment]
说说我的想法，拼音转换其实比较适合在服务端做，因为完整的拼音字典是比较大的，在浏览器端做完整的拼音转换支持，开销比较大；不做完整的支持，实用性又比较差，所以最好还是推荐在服务端做，哪怕是服务端提供个接口供客户端使用，也比直接在客户端使用合适。

**Comment by janryWang** [comment]
@hotoo 这个真的不是服务端吐的数据，就是前端生成的，要哭了。。。

**Comment by hotoo** [comment]
不能在服务端提供个 http/rpc 接口，做拼音转换的服务吗？

**Comment by janryWang** [comment]
不能，我要做的是一个通用组件，不依赖任何业务数据的

**Comment by hotoo** [comment]
拼音转换服务也是通用服务，并不是业务数据吧。

在客户端转换拼音我再考虑下吧。
前端容易手里有把锤子，放眼都是钉子。不要把自己限制在客户端。

**Comment by janryWang** [comment]
依赖后端容易有副作用，后端挂了，组件就挂了

**Comment by hotoo** [comment]
。。。

**Comment by iclear** [comment]
有时候,确实有这个需求.
最好提供选项,字库可以选择完整版或简单版

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`
