### ISSUE TITLE
"茜"只有qian，没有xi

### ISSUE THREAD

**Issue by shuai-z** [hotoo/pinyin#167]

**Comment by hotoo** [comment]
这个字还真不读 xi

**Comment by shuai-z** [comment]
Unihan Database 中 kHanyuPinyin 是有的哦

https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E8%8C%9C

**Comment by hotoo** [comment]
也许未来会读 xi 吧，现在都读 说(shuo)服 了
