### ISSUE TITLE
建议加入“绚”

### ISSUE THREAD

**Issue by dorkpon** [hotoo/pinyin#172]
绚也是常用字，建议加入

https://github.com/hotoo/pinyin/blob/d245b1284ea3b3c6a29e212efe7525243a7e4bcd/data/dict-zi-web.js#L1397

**Comment by hotoo** [comment]
Web 版用的是国标的 3000多个常用字库，实际常用字还有很多，而完整的字库会比较大，建议使用服务端使用 Node 版转换并持久化。
