### ISSUE TITLE
Unexpected token: name (hans)

### ISSUE THREAD

**Issue by yurentle** [hotoo/pinyin#179]
用webpack打包的时候报错：
0.7ab91a7d.async.js from UglifyJs
Unexpected token: name (hans) [0.7ab91a7d.async.js:14991,6]
  #

**Comment by metrue** [comment]
same issue.

**Comment by Zertu** [comment]
出现了同样问题，有解决的么

**Comment by yurentle** [comment]
@Zertu 降低版本就行了，我用的2.0.0

**Comment by Zhouqchao** [comment]
same issue. 
![pinyin-build-error](https://user-images.githubusercontent.com/24250131/42867790-3940d4c6-8aa3-11e8-920c-c0c1e23fbb18.png)

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`
