### ISSUE TITLE
蔡字不能转换

### ISSUE THREAD

**Issue by hjd521** [hotoo/pinyin#183]
console.log(pinyin("蔡亚明", {
  style: pinyin.STYLE_FIRST_LETTER, // 设置拼音风格
  heteronym: true
}));

结果：Array[0]："蔡"

**Comment by gosp** [comment]
const alias = pinyin('蔡亚明', {
        style: pinyin.STYLE_FIRST_LETTER
    }).join('');
    console.log(alias); // cym

**Comment by hotoo** [comment]
建议使用服务端使用 Node 版转换并持久化。

**Comment by ailaiwuyou** [comment]
蔡健雅无法转换  岑宁儿的首字母也无法转换

**Comment by hotoo** [comment]
升级到 v2.9.0
