### ISSUE TITLE
为什么是默认使用dict-zi-web.js

### ISSUE THREAD

**Issue by Dodo703** [hotoo/pinyin#188]
我先是npm安装 "pinyin": "^2.8.3"，webpack里面的配置
![qq 20180316173501](https://user-images.githubusercontent.com/19563091/37513612-83adc0b0-2940-11e8-82a9-58a5ab713ec3.png)

然后组件里面使用import pinyin from 'pinyin'，
我感觉我还是用的dict-zi-web.js字库，不是用的dict-zi.js的库，我想用全一点的库，应该在哪里修改啊
![image](https://user-images.githubusercontent.com/19563091/37513650-9e0af3f6-2940-11e8-922f-850b17ba0d79.png)
我可以在node_modules里面去加，可是我只是上传package.json，不会去上传node_modules到svn，我怎么保证我改的呢，我就想默认使用dict-zi.js的库

![qq 20180316175415](https://user-images.githubusercontent.com/19563091/37514531-2e2c5f90-2943-11e8-8faa-b5ffd33631dd.png)

**Comment by hotoo** [comment]
完整字库比较大，放在 Web 端不是特别合适。建议在服务端转换拼音并持久化。
另外也在考虑不区分 Node 和 Web 端的字库区别的问题，可能在 3.0 解决。

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`，Web browser 和 Node.js 版都使用了完整的字库。
