### ISSUE TITLE
请问下那个兼容IE的dist怎么用啊？

### ISSUE THREAD

**Issue by codeshareman** [hotoo/pinyin#190]
您好，我觉得您的pinyin库挺好用的，并且您也提供了兼容IE的dist方案，但是我将lib下的web-pinyin.js替换了之后没有什么效果，这是为啥呢？请指教下，谢谢

**Comment by hotoo** [comment]
由于完整版的拼音库比较大，建议您字服务端使用 Node 版并持久化。
