### ISSUE TITLE
“迪”不能被转换

### ISSUE THREAD

**Issue by danranshizhi** [hotoo/pinyin#193]
“迪”不能被转换
pinyin("芯迪科技", {
      style: pinyin.STYLE_NORMAL,
      heteronym: true
    }).toString().replace(/,/g,'')+new Date().getTime()
得到的结果为“xin迪keji1525311623271”，这个要怎么改？

**Comment by hotoo** [comment]
建议字服务端使用 Node 转换后持久化。
