### ISSUE TITLE
了= le | liao / choice based on frequency

### ISSUE THREAD

**Issue by dcsan** [hotoo/pinyin#195]
Are there some settings to choose the most frequent case?

this library seems to default `了=liao` 
Of course there is `不得了 budeliao` but that is much less frequent.
so this causes many problems.

![image](https://user-images.githubusercontent.com/514002/39803024-46dd8e04-53a2-11e8-9309-f8e86d82229c.png)

![image](https://user-images.githubusercontent.com/514002/39803036-4d06b468-53a2-11e8-9b58-0b3e7d1b73fa.png)

now I have to do this:

```js
const SPECIAL_CASE_PINYIN = {
  "了": "le",
  "除了": "chúle",
  "还是": "háishi",
  "还有": "háiyou",
  "还": "hái",
  "都":"dōu",
  "什么": "shénme",
  "怎么": "zěnme",
  "那么": "nàme",
  "为什么": "wéishěnme",
  "怎么样": "zěnmeyang",
  "太好了": "tàihǎole"
}
```

**Comment by hotoo** [comment]
PR is welcome.
