### ISSUE TITLE
吗字顺序问题

### ISSUE THREAD

**Issue by sytana** [hotoo/pinyin#199]
![image](https://user-images.githubusercontent.com/11701135/40275867-2c863bc0-5c2e-11e8-871f-58c6afd7e1b7.png)

没有声调的是不是应该放在前面呢，因为在组成的时候默认用第一个

**Comment by hotoo** [comment]
欢迎 PR

**Comment by sytana** [comment]
![image](https://user-images.githubusercontent.com/11701135/40277282-b98f339e-5c4e-11e8-9321-38079ab58f95.png)
