### ISSUE TITLE
用在react中，用webpack打包后，ie 11里面总是报 script1002语法错误

### ISSUE THREAD

**Issue by danranshizhi** [hotoo/pinyin#201]
你好，用在react中，使用webpack打包后，在谷歌，火狐浏览器都没有问题，在ie11中总是报script1002语法错误,定位的错误行为   class Pinyin{}这一行，请问一下，这个问题，您有好的处理方法吗，感谢！

**Comment by linonetwo** [comment]
这明显就是没有转换成ES3，babel loader 配一下。

**Comment by linonetwo** [comment]
那肯定啊，ie 哪来的 class

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`
