### ISSUE TITLE
“哦”字没有被解析成拼音，直接是['哦']

### ISSUE THREAD

**Issue by wsxz00** [hotoo/pinyin#202]
“哦”字没有被解析成拼音，直接是['哦']

**Comment by evayde** [comment]
Same with 倩 it will directly be assigned to 倩

对不起，我写英语，因为我的中文不好.

**Comment by hotoo** [comment]
没关系，我英文也不好。

Pinyin support you use it on web and node, but just with part of pinyin dictionary on web, because  the full dictionary  is too lary.

I suggest you to use pinyin on the node, and persistence pinyin result(like save to database). This is the best practices on pinyin.

**Comment by andyhu** [comment]
This isn't ideal... The web version is somewhat crippled. Have you considered to cache it into localstorage in the browser?
By the way, if you don't need to mark those tones and you are ok with occasional polyphone issues, try `transliteration`

**Comment by hotoo** [comment]
请更新到 v2.9.0
Upgrade to v2.9.0 please.
