### ISSUE TITLE
“石” 多音字的问题

### ISSUE THREAD

**Issue by zhengyeye** [hotoo/pinyin#206]
山西-石头 shanxi-shitou，是正确的；
山西-石库  shanxi-shi,danku ,但是这里应该是shiku ，现在是danku连一起，
我已经
```javascript
style: pinyin.STYLE_FIRST_LETTER,
heteronym: true,
segment: true
```
请问这个问题应该怎么合理的解决？

**Comment by hotoo** [comment]
这个返回的其实是个二维数组，你可以从中选取需要的部分。

```json
[
  ['shan'],
  ['xi'],
  ['-'],
  ['shi','dan'],
  ['ku']
]
```

出现这个不同，是因为 “石头” 在词组库里，并且被识别为一个词了，而“石库”未能识别为一个词，您开启了`heteronym: true`，所以直接返回了石字的所有拼音。

还有一个办法，你可以考虑关闭 `heteronym: false` 试试，这种情况下默认取用第一个拼音。

**Comment by zhengyeye** [comment]
好的，谢谢你了。
