### ISSUE TITLE
在 Web 版中可选地启用分词器

### ISSUE THREAD

**Issue by linonetwo** [hotoo/pinyin#211]
希望能在选项里传入一个分词函数用于分词，目前有 https://github.com/linonetwo/segmentit 这个库可以使用，让 electron 或者 chrome extension 开发者也可以用上更精确的拼音转换。

**Comment by hotoo** [comment]
谢谢提供资讯，我尽快考虑如何处理。

**Comment by hotoo** [comment]
3.x 中已经支持。`npm i pinyin@alpha`

**Comment by linonetwo** [comment]
牛啊

**Comment by hotoo** [comment]
@linonetwo 放了 3 年半 😂

你啥时候给 segmentit 加个 ts 类型定义呗。

**Comment by linonetwo** [comment]
应该不难，现在就是 class 写的，可能我用 ts 跑一下就有了

**Comment by zerooverture** [comment]
segment 设置为false 打包的时候依旧有 segmentit包 可否设置成不引入?

**Comment by hotoo** [comment]
@zerooverture 你可以在打包配置 segmentit 为 external 库，然后自己定义一个空对象即可。

另外，不相关的请另提 issue。
