### ISSUE TITLE
“了”字

### ISSUE THREAD

**Issue by shiny** [hotoo/pinyin#213]
吃了吗 => [ [ 'chī' ], [ 'liǎo' ], [ 'má' ] ]
来了 => [ [ 'lái' ], [ 'liǎo' ] ]

正常情况下 le 应该概率更高？

**Comment by shiny** [comment]
看到了相关 issue #195

**Comment by shiny** [comment]
请问如何获取 2cf8d4db1c40effbaf81b0485538ecc11f6d5e71 的更新？npm 安装的不是最新的

**Comment by hotoo** [comment]
安装最新版的 pinyin 就可以了。
