### ISSUE TITLE
react中npm run build报错

### ISSUE THREAD

**Issue by danranshizhi** [hotoo/pinyin#219]
在react中使用该插件，执行npm run build后，报错 
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/pinyin/lib/web-pinyin.js:7

Read more here: http://bit.ly/2tRViJ9

请问这种情况要怎么处理?

**Comment by mofelee** [comment]
遇到了同样的问题

**Comment by mofelee** [comment]
https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify

官方的解决方案，升级create-react-app 到2.x就行

**Comment by hotoo** [comment]
楼上正解。
