### ISSUE TITLE
用了分词和多音字，但是输入时重庆时，返回的多音字还是一个列表。

### ISSUE THREAD

**Issue by darkSideOfMoon** [hotoo/pinyin#220]
![image](https://user-images.githubusercontent.com/42800681/46138896-bbab4900-c27f-11e8-8a99-42fe3d22eebf.png)

**Comment by hotoo** [comment]
请查看文档，多音字模式就是会返回汉字对应的所有可能的拼音，`重` 字是多音字，所以会返回 2 个读音。
另外浏览器端执行的，不支持 segment: true
