### ISSUE TITLE
部分遗落的字

### ISSUE THREAD

**Issue by darkSideOfMoon** [hotoo/pinyin#222]
作者还在更新么？下面的字被遗落了
亳bó州、儋dān州、喀kā什、忻xīn州、朔shuò州、汕shàn头（尾）、泸lú州、淄zī博、湛zhàn江、滁chú州、滦luán县、漯luò河、漳zhāng州、潍wéi坊、濮pǔ阳、绥suí化、肇zhào庆、莆pú田、菏hé泽、衢qú州、襄xiāng阳、赣gàn州、邯郸hándān、邵shào阳、郴chēn州、鄂è尔多斯（州）、阜fù新（阳）、陇lǒng南、韶sháo关

**Comment by darkSideOfMoon** [comment]
我按照字典里的格式写了一份，你补一下吧
"亳州":[["bó"],["zhōu"]],
"郴州":[["chēn"],["zhōu"]],
"滁州":[["chú"],["zhōu"]],
"儋州":[["dān"],["zhōu"]],
"鄂尔多斯":[["è"],["ěr"],["duō"],["sī"]],
"鄂州":[["è"],["zhōu"]],
"阜新":[["fù"],["xīn"]],
"阜阳":[["fù"],["yáng"]],
"赣州":[["gàn"],["zhōu"]],
"邯郸":[["hán"],["dān"]],
"菏泽":[["hé"],["zé"]],
"喀什":[["kā"],["shí"]],
"陇南":[["lǒng"],["nán"]],
"泸州":[["lú"],["zhōu"]],
"滦县":[["luán"],["xiàn"]],
"漯河":[["luò"],["hé"]],
"莆田":[["pú"],["tián"]],
"濮阳":[["pú"],["yáng"]],
"衢州":[["qú"],["zhōu"]],
"汕头":[["shàn"],["tóu"]],
"汕尾":[["shàn"],["wěi"]],
"邵阳":[["shào"],["yáng"]],
"韶关":[["sháo"],["guān"]],
"朔州":[["shuò"],["zhōu"]],
"绥化":[["suí"],["huà"]],
"潍坊":[["wéi"],["fāng"]],
"襄阳":[["xiāng"],["yáng"]],
"忻州":[["xīn"],["zhōu"]],
"淄博":[["zī"],["bó"]],
"湛江":[["zhàn"],["jiāng"]],
"漳州":[["zhāng"],["zhōu"]],
"肇庆":[["zhào"],["qìng"]],

**Comment by darkSideOfMoon** [comment]
第一个字典里面也加一下
"luò":'漯',
"dān":'儋',
"kā":'喀',
"xīn":"忻",
"shuò":"朔",
"shàn":"汕",
"lú":"泸",
"zī":"淄",
"zhàn":"湛",
"chú":"滁",
"luán":"滦",
"zhāng":"漳",
"wéi":"潍",
"pú":"濮",
"suí":"绥",
"zhào":"肇",
"pú":"莆",
"hé":"菏",
"qú":"衢",
"xiāng":"襄",
"gàn":"赣",
"hán":"邯",
"dān":"郸",
"shào":"邵",
"chēn":"郴",
"è":"鄂",
"fù":"阜",
"lǒng":"陇",
"sháo":"韶",

**Comment by hotoo** [comment]
请更新到  v2.9.0
