### ISSUE TITLE
angular下使用，ie报错。

### ISSUE THREAD

**Issue by Liiiiimo** [hotoo/pinyin#224]
在angular下使用，谷歌浏览器正常运行，但是在ie浏览器报错，导致整个路由加载失败。渣渣表示不知道啥原因.....

**Comment by hotoo** [comment]
没有提供详细的错误信息，无法判断问题所在。

由于本库使用了 ES6 语法，而 Chrome 已经支持 ES6，你用的 IE 浏览器目前默认还不支持，再不编译成 ES5 的情况会报错。这种情况下，你需要一个编译器，例如 babeljs.io
