### ISSUE TITLE
有些城市的名称没法转拼音

### ISSUE THREAD

**Issue by czy66545360** [hotoo/pinyin#228]
"zhao": "肇",
  "luo": "漯",
  "zhan": "湛",
  "chen": "郴",
  "dan": "儋",
  "zhang": "漳",
  "shao": "邵韶",
  "e": "鄂",
  "qu": "衢",
  "han": "邯",
  "di": "迪",
  "lu": "泸",
  "long": "陇",
  "gan": "赣",
  "quan": "荃",
  "shuo": "朔",
  "xin": "忻",
  "sui": "绥",
  "ka": "喀",
  "xiang": "襄",
  "fu": "阜",
  "zi": "淄",
  "he": "菏",
  "wei": "潍渭",
  "bo": "亳",
  "chu": "滁",
  "pu": "莆濮",

这些是我手动加的   这些文字都没有拼音   希望 能补充上

**Comment by hotoo** [comment]
请升级到 v2.9.0
