### ISSUE TITLE
温字能转拼音，但是没有首字母

### ISSUE THREAD

**Issue by HaoPengZheng** [hotoo/pinyin#233]
var pinyin = require('pinyin')
console.log(pinyin('温', {style: pinyin.STYLE_INITIALS}))

**Comment by hotoo** [comment]
https://github.com/hotoo/pinyin#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89-y-w-yu-%E5%87%A0%E4%B8%AA%E5%A3%B0%E6%AF%8D
