### ISSUE TITLE
“着”的拼音不正确

### ISSUE THREAD

**Issue by xiangyuecn** [hotoo/pinyin#240]
https://github.com/hankcs/HanLP/issues/1093 这个库也有这个问题

> 使用转拼音功能时，发现汉字“着”在任何时候都输出了“zhuó”，但是其实大多数应该输出“zhe”的。
>
> 比如：盼望着盼望着，春天来了；功名浑是错，更莫思量着；悄没声的河沿上，满铺着寂寞和黑暗；我从山中来，带着兰花草。。等等这些句子里的“着”都输出了拼音“zhuó”，但是明显应该是“zhe”

**Comment by hotoo** [comment]
这个库的多音字支持确实不完善，你有好的建议或意见可以提出来，也可以直接提交 PR

**Comment by xiangyuecn** [comment]
哈哈，大佬们都没有办法我就更没有办法啦😜

close now😊
