### ISSUE TITLE
一个建议，可能实现了，我就是说说

### ISSUE THREAD

**Issue by YSHIDM** [hotoo/pinyin#244]
能不能把api柯里化，例如：fun({opt})('汉字');
let getPinyinDuoyin = fun({多音字});
getPinyinDuoyin('汉字');
let getPinyinFenci = fun({多音字,分词});
getPinyinFenci ('汉字');
当然，其实大家可以自己封装。

**Comment by hotoo** [comment]
你先自己封装吧 ：）
