### ISSUE TITLE
根本不支持多音字。。。。

### ISSUE THREAD

**Issue by wangkaisine** [hotoo/pinyin#247]
[root@bin]# ./pinyin 桔子
jié zǐ
[root@bin]# ./pinyin 淡薄
dàn báo
[root@bin]# ./pinyin 薄雾
báo wù
[root@bin]# ./pinyin 开会
kāi huì
[root@bin]# ./pinyin 会计
huì jì
[root@bin]# ./pinyin 着火
zhuó huǒ
[root@bin]# ./pinyin 穿着
chuān zhuó
[root@bin]# ./pinyin 看着
kàn zhuó
[root@bin]# ./pinyin 劳模
láo mó
[root@bin]# ./pinyin 模具
mó jù

**Comment by hotoo** [comment]
1. 多音字是指一个字有多个读音，你需要多个读音需要对应的 `-h` 参数。
2. 你这里表达的多音字应该是根据短语上下文自动识别正确的读音，这不是默认的，也需要加 `-S` 参数。即便如此，这个多音字识别的准确率也还是有很大差距。你有好的建议或意见可以提出来，抱怨没任何意义。

```
$ pinyin -S 会计
kuài jì

$ pinyin -h 着  
zhuó,zháo,zhāo,zhe
```

**Comment by LiuSandy** [comment]
> 1. 多音字是指一个字有多个读音，你需要多个读音需要对应的`-h`参数。
> 2. 你这里表达的多音字应该是根据某种之上的自动识别正确的读音，这不是唯一的，也需要加`-S`参数。还要如此，这个多音字识别的准确率也还是有很大的优化空间。你有好的建议或意见可以提出来，怀疑没任何意义。
> 
> ```
> $ pinyin -S 会计
> kuài jì
> 
> $ pinyin -h 着  
> zhuó,zháo,zhāo,zhe
> ```

我怎么在node里面使用，
>```
>const chineseList = pinyin("适应症", {
>     style: pinyin.STYLE_NORMAL,
>     heteronym: true,
>     segment: true
>   });
> console.log("chineseList",chineseList)
> [["kuo", "shi"],["ying"],["zheng"]]
>```
>
