### ISSUE TITLE
拼音翻译乱码

### ISSUE THREAD

**Issue by FridayDai** [hotoo/pinyin#259]
浏览器为chrome77版本，mac上没问题，windows机器有问题，会出现如下问题，请问下这个怎么办？
![image](https://user-images.githubusercontent.com/17562811/65650969-84f94180-e03f-11e9-87e8-10568e4641e6.png)
![image](https://user-images.githubusercontent.com/17562811/65650988-95112100-e03f-11e9-8be7-b72094999d1a.png)

**Comment by hotoo** [comment]
你是在客户端使用吗？没有中 windows 测试过。建议中 Nodejs 服务端使用 pinyin 模块。
