### ISSUE TITLE
怎么把STYLE_TONE2 ，shi4   luo4  这种形式的，转成声调

### ISSUE THREAD

**Issue by zhaolu678** [hotoo/pinyin#260]
STYLE_TONE2
luo4 ->luò
这样怎么转换？？

**Comment by theajack** [comment]
这个支持音调：[cnchar](https://github.com/theajack/cnchar)

```js
'测试'.spell('tone')
```

而且功能很全，不光拼音，还有笔画笔顺繁简体等

**Comment by hotoo** [comment]
@zhaolu678 为什么不直接使用 TONE 模式？
