### ISSUE TITLE
元音字母开头的汉字（a, e, o）在安卓机上测试排序不正确

### ISSUE THREAD

**Issue by naliomg** [hotoo/pinyin#261]
元音字母开头的汉字（a, e, o）在安卓机上测试排序不正确，被排到了最后。

**Comment by naliomg** [comment]
看来用 localeCompare 进行排序还是依赖环境啊...

**Comment by rogerus** [comment]
阿，鹅，排到一起是对的。汉字没有元音开头的字，aeoyw开头的其实都是省略了声母的写法。这些字的声母都是一个喉塞音，也就是汉语音韵里所谓的影母。如果没有这个喉塞音声母，就会出现跟法语类似的连诵现象。所以，作者这样的设定，是正确并且专业的。
