### ISSUE TITLE
“只”只会转换为zhī

### ISSUE THREAD

**Issue by markalexander** [hotoo/pinyin#265]
你好，

“只”只会转换为zhī，但在大多数情况下，应该为zhǐ。 我认为这种罕见的形式是用于简化的“隻”的。

预期行为：

    pinyin("只")
    [ [ 'zhǐ' ] ]
    pinyin("我只要")
    [ [ 'wǒ' ], [ 'zhǐ' ], [ 'yào' ] ]

实际行为：

    pinyin("只")
    [ [ 'zhī' ] ]
    pinyin("我只要")
    [ [ 'wǒ' ], [ 'zhī' ], [ 'yào' ] ]

**Comment by hotoo** [comment]
请开启分词

```bash
$ pinyin -hS 只要
zhǐ yào
$ pinyin -hS 我只要
wǒ zhǐ yào
```
