### ISSUE TITLE
通过npm安装的包里面是es6，，，不太合适吧

### ISSUE THREAD

**Issue by davidwang1988** [hotoo/pinyin#268]
求发布转义过的包，否则按正常babel都会设置exclude node_modules 导致打包后还有es6

**Comment by juenanfeng** [comment]
+10086

**Comment by zlx1134558955** [comment]
可以试一下pinyin-pro

**Comment by hotoo** [comment]
pinyin 属于比较大的库，推荐在 Node 端使用。node 支持 ES6
