### ISSUE TITLE
阿  有问题

### ISSUE THREAD

**Issue by qiz264** [hotoo/pinyin#274]
‘阿’ 和 ‘啊’  排序结果不同

const data = '此波啊'.split('');
const sortedData = data.sort(pinyin.compare);

===>   ["啊", "波", "从"]
正确

const data = '此波阿'.split('');
 const sortedData = data.sort(pinyin.compare);

===>   ["波", "此", "阿"]
错误

**Comment by jiyuan12354** [comment]
多音字，没有智能排序

**Comment by hotoo** [comment]
![image](https://user-images.githubusercontent.com/143572/114305242-ccec9600-9b09-11eb-9270-17bfb5bacdf9.png)

我看了下没问题，你在 Node 端试试呢。
