### ISSUE TITLE
Mac下对英文的处理结果和Windows、Linux不同

### ISSUE THREAD

**Issue by 17forever** [hotoo/pinyin#277]
你好，感谢这个优秀的工具，解决了我很大的问题。
我在开发中发现，对同一段英文的文本，比如 nextjs-with-styled-components-fluent-ui

Windows和Linux下处理正常，如下
![6571599493353_ pic_hd](https://user-images.githubusercontent.com/11835233/92549149-38783780-f28b-11ea-9073-b74c12d98074.jpg)

Mac下会多包一层数组，如下
![6501599449499_ pic](https://user-images.githubusercontent.com/11835233/92549157-3c0bbe80-f28b-11ea-9a9b-5183cbe814e2.jpg)

**Comment by Brooooooklyn** [comment]
试一下 https://github.com/Brooooooklyn/pinyin

**Comment by hotoo** [comment]
我看你两个截图的结构是一样的，你仔细看看。
