### ISSUE TITLE
拼音字典 pinyin/data/dict-zi.js 里有空格

### ISSUE THREAD

**Issue by uscq** [hotoo/pinyin#278]
如下几行：
dict[0x411c] = "lí,chī ";
dict[0x21464] = "luǒ,yíng ";
dict[0x23aba] = "hú ";

是有意而为之吗？

**Comment by uscq** [comment]
词组注音看上去有错的：
["别鹤离鸾"] = { "bié", "hè", "lí", "láun" }, -> luán
["畏首畏尾"] = { "wèi", "shǒ", "wèi", "wěi" }, ->shǒu
["飞将数奇"] = { "fē", "jiàng", "shù", "jī" }, -> fēi
["支分族解"] = { "zhī", "fē", "zú", "jiě" }, -> fēn
["昂昂自若"] = { "áng", "áng", "zì", "roò" }, -> ruò
["失败为成功之母"] = { "shī", "bài", "wéi", "chéng", "gōng", "zhī", "m" },
["年华垂暮"] = { "nián", "huá", "thuí", "mù" },
["操戈同室"] = { "cāo", "gē", "tóon", "shì" },
["缺吃少穿"] = { "quē", "chī", "xhǎo", "chuān" },
["枝干相持"] = { "zhī", "gàn", "xiāng", "hí" },
["餐松啖柏"] = { "cān", "sōng", "dàn", "biǎ" },
["拱肩缩背"] = { "gǒng", "jān", "suō", "bèi" },
["不破不立"] = { "bù", "può", "bù", "lì" },
["虮虱相吊"] = { "jǐ", "shī", "xiēng", "diào" },
["风云变幻"] = { "fēng", "yún", "bià", "huàn" },
["偏听偏信"] = { "piān", "tīng", "piāng", "xìn" },
["枝叶相持"] = { "zhī", "yè", "xīng", "chí" },
["斯事体大"] = { "ī", "shì", "tǐ", "dà" },
["帝王将相"] = { "dì", "wáng", "jiòn", "xiàng" },

["āi"] = "哎哀埃娭溾嗳銰锿噯諰鎄"，要加 “诶”

**Comment by hotoo** [comment]
你其实可以直接提交 PR
