### ISSUE TITLE
俞佳莹会转化为shujiaying

### ISSUE THREAD

**Issue by youki666** [hotoo/pinyin#281]
俞佳莹会转化为shujiaying

**Comment by Brooooooklyn** [comment]
试一下 https://github.com/Brooooooklyn/pinyin

**Comment by M69W** [comment]
> 试一下 https://github.com/Brooooooklyn/pinyin

已经在两个issues看到你推自己的仓库
老实说，在解决上面的问题后（思路或问题所在等等），再对比两者之间的差异

相信使用的人自有选择

**Comment by Brooooooklyn** [comment]
> 已经在两个issues看到你推自己的仓库

我只是在本仓库存在并且暂时没有修复计划的 issue 下推荐，相信应该不会对这个库的维护者们造成困扰

> 老实说，在解决上面的问题后（思路或问题所在等等），再对比两者之间的差异，相信使用的人自有选择

仓库 README 中已经写的很清楚了

**Comment by M69W** [comment]
【俞】此字是多音字，也是楼主想解决的问题
通过对此仓库的搜索：https://github.com/hotoo/pinyin/search?q=%E4%BF%9E&type=issues
只看到两个关于【俞】这个字的issues，
其中一个issues 就 说到 @/issues/34，里面也提供【临时】解决方法。例如 @/issues/34

**Comment by hotoo** [comment]
![image](https://user-images.githubusercontent.com/143572/98462469-970c5400-21ef-11eb-85e8-0701a2d641a9.png)

没有遇到你的问题呢，麻烦给下复现方式
