### ISSUE TITLE
options.group: true 无效

### ISSUE THREAD

**Issue by ezhaohongwei** [hotoo/pinyin#287]
### 版本
"pinyin": "^2.9.1"
### 测试
console.log(pinyin("我喜欢你", {
        segment: true,                // 启用分词
        group: true                   // 启用词组
}));
### 结果
wǒ xǐ huān nǐ

查了源码，并没有说明里的group参数。不在这个版本里吗？

**Comment by hotoo** [comment]
pinyin@2.10.0
