### ISSUE TITLE
有没有人名模式？

### ISSUE THREAD

**Issue by BarneyRoos** [hotoo/pinyin#288]
人名中的多音字读音固定，希望能配置个人名模式

**Comment by BarneyRoos** [comment]
针对姓氏

**Comment by hotoo** [comment]
我也想过这个，但是苦于一直没有合适的分词库支持识别人名的能力。

**Comment by CarterLi** [comment]
直接用参数指定一下可以吗？比如说 `lastName: true`

用于解决这类需求：

![image](https://user-images.githubusercontent.com/6134068/144398343-cc155d60-dd60-4e03-95df-c07b1dd8e8b6.png)

**Comment by my-mini-react** [comment]
可以尝试下[pinyin-pro](https://github.com/zh-lx/pinyin-pro)，支持人名模式

**Comment by BarneyRoos** [comment]
亲，你的信我已收到，真希望尽快看到它！

**Comment by hotoo** [comment]
+ pinyin@2.11.0
