### ISSUE TITLE
"哦" 无法转换转拼音

### ISSUE THREAD

**Issue by heypig** [hotoo/pinyin#290]
![image](https://user-images.githubusercontent.com/1009794/110610743-7a961d80-81c9-11eb-81a9-5559d8cdbbc2.png)

**Comment by zlx1134558955** [comment]
可以看一下pinyin-pro项目

**Comment by M69W** [comment]
楼主还是用了上面推荐的吧
毕竟他每个issue都推荐

蛮辛苦的，说不定能解决你的问题对吧

**Comment by M69W** [comment]
不必用小号，直接上大号吧
