### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by tianxiagu** [hotoo/pinyin#297]

**Comment by tianxiagu** [comment]
当转地名的时候,例如阿富汗,首字母会是e不应该是a吗?

**Comment by zq0904** [comment]
遇到同样的问题 这个看起来像是多音字 导致的

还有node环境 和web环境体验不一致
阿 
阿党相为 "ē"
阿富汗 "ā"

你可以自己fork dict-zi-web.js 修改下 "ā,ē": "阿"
