### ISSUE TITLE
“中文” 在 STYLE_INITIALS 下获得 [['zh'], ['']]

### ISSUE THREAD

**Issue by ultravires** [hotoo/pinyin#303]
expect `[['zh'], ['w']]`

fail: `expect(pinyin('中文', { style: pinyin.STYLE_INITIALS })).toEqual([['zh'], ['w']]);`

**Comment by hotoo** [comment]
https://github.com/hotoo/pinyin#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89-y-w-yu-%E5%87%A0%E4%B8%AA%E5%A3%B0%E6%AF%8D
