### ISSUE TITLE
建议新增一个紧凑的输出方法

### ISSUE THREAD

**Issue by ultravires** [hotoo/pinyin#304]
建议新增一个 `compact` 方法，将多音字词的输出变为紧凑的，方便比较匹配。如：`”还好“ ：[['hai', 'hao'], ['huan', 'hao']]`

这样用户输入 “haihao” 关键字进行查找的时候可以方便的调用 `join()` 方法进行匹配。

`
expect(pinyin('全体成员', { style: pinyin.STYLE_FIRST_LETTER, heteronym: true }).compact()).toEqual([['q', 't', 'c', 'y'], ['q', 'b', 'c', 'y']]);
`

**Comment by hotoo** [comment]
提议很好， @ultravires 你有兴趣提 PR 吗？

**Comment by ultravires** [comment]
> 提议很好， @ultravires 你有兴趣提 PR 吗？

已经提交 PR 了，看下能否通过
