### ISSUE TITLE
建议升级nodejieba到最新版本

### ISSUE THREAD

**Issue by ryanelee** [hotoo/pinyin#308]
目前使用的可选依赖nodejieba版本会导致npm audit通不过。能否升级到最新版本？

"optionalDependencies": {
    "nodejieba": "^2.2.1"
  },

`# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/strip-ansi
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/string-width

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix`

**Comment by WumaCoder** [comment]
我今天早上也因为这个问题，缺少nodejieba依赖，导致线上的服务器出现了问题

**Comment by ryanelee** [comment]
@WumaCoder 应该是之前某个版本把peerDependencies改成optional了。

https://github.com/hotoo/pinyin/commit/f13f161a401167ea1427ad446f58517cbaabfb44#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by hotoo** [comment]
@ryanelee 依赖写的是 `^2.2.1`，而 nodejieba 最新版是 2.5.x，是匹配的。

@WumaCoder 如果你的项目确实需要 nodejieba，可以考虑自己依赖，这样安装的时候就能发现是否正常了。

**Comment by WumaCoder** [comment]
> @ryanelee 依赖写的是 `^2.2.1`，而 nodejieba 最新版是 2.5.x，是匹配的。
> 
> @WumaCoder 如果你的项目确实需要 nodejieba，可以考虑自己依赖，这样安装的时候就能发现是否正常了。

只能这样了
