### ISSUE TITLE
注音、笔顺、部首、结构、异体字、五笔、仓颉等数据

### ISSUE THREAD

**Issue by qaqz111** [hotoo/pinyin#31]
之前自己搜集了汉字包括拼音和**注音、笔顺、部首、结构分析、异体字、五笔码、仓颉码等等**方面的数据，虽然多出来的部分已经不在拼音的范畴内，传上来看能不能用得上，做扩展插件或者加强版之类的。

非常感谢这个项目！

![hanziinfo](https://cloud.githubusercontent.com/assets/3367034/5788369/b8658a20-9e6c-11e4-9900-d0ed95e747a1.png)

(不能上传7z，所以弄成了图片档，更改扩展名为.rar可以用7z或者rar打开)

如果不需要的话请管理员删除。

**Comment by hotoo** [comment]
感谢你的分享。

不过下载有点慢，最好存在百度云盘之类的地方分享出来，把分享地址贴这里。

**Comment by qaqz111** [comment]
噢，好的，这是百度云盘的链接，希望能够有用。

http://pan.baidu.com/s/1eQgXc6A

数据格式是Json，下面是各个文件内容的说明：
- 汉字拼音.js ：拼音部分，仅一个对象，key是汉字的Unicode码的十进制形式，数据是拼音的数组。
- 汉字注音.js ：注音，格式同上。
- 汉字笔顺.js ：笔顺，格式同上，是用【一丨ノ丶フ】表示的，要转换为数字只要简单替换即可。
- 汉字数据-UTF16.js ：汉字信息的全部数据，但是只包括U+FFFF之前的部分，即UTF-16部分。
- 汉字数据-UTF32.js ：汉字信息的全部数据，但是只包括U+FFFF之后的部分，即UTF-32部分。
- 汉字数据-ALL.js ：上面两个文件的组合。

后面三个文件是一行一个Json对象，因为数据量很大所以没有做成一个完整对象的形式，否则反序列化的时候可能会很恼火。所以如果要在js的代码里用的话可能需要重新处理一下，但是应该都很简单。

**Comment by hotoo** [comment]
非常棒的数据，感谢你的慷慨分享 ：）
