### ISSUE TITLE
对GB18030-2005字符集支持不完整，部分中文原样输出导致输入法解析失败。

### ISSUE THREAD

**Issue by chinsyo** [hotoo/pinyin#325]
可参考输入引擎rime的字库[essay.txt](https://raw.githubusercontent.com/rime/librime/master/data/minimal/essay.txt)，词频最低的单字（文件最下方）大都无法转换。建议无法解析的单字输出异常而不是原样输出。

𫗴	0
𫘝	0
𫘨	0
𫚕	0

**Comment by chinsyo** [comment]
> 如果输出异常，那么对于有标点和英文（其他国家文字等）、Emoji 等的一段文字就无法处理了。不过可以考虑增加一个 strict 参数，来指定异常处理的不同方式。

是的，可参考python中str.encode的errors参数添加下。

**Comment by hotoo** [comment]
@chinsyo 看了你举例的几个汉字，包括汉典在内都没有对应的拼音信息：

- [𫗴](https://www.zdic.net/hans/%F0%AB%97%B4)
- [𫘝](https://www.zdic.net/hans/%F0%AB%98%9D)
- [𫘨](https://www.zdic.net/hans/%F0%AB%98%A8)
- [𫚕](https://www.zdic.net/hans/%F0%AB%9A%95)

这些扩展字如果都没有准确读音的话，对于 pinyin 库来加不加对应的汉字，都没有什么影响的样子。
