### ISSUE TITLE
Issues with tones and word segmentation

### ISSUE THREAD

**Issue by JanVeb** [hotoo/pinyin#336]
Here are my examples that are have errors, and that can even I figure out on my own, even though I don't speak Chinese

example 1
請問你是陳月美小姐嗎？

it translates it into
0: ['qǐngwèn']
1: ['nǐ']
2: ['shì']
3: ['chén']
4: ['yuè']
5: ['měi']
6: ['xiǎojiě']
7: ['má']
8: ['？']

while correct is Qǐngwèn nǐ shì Chén Yuèměi xiǎojiě ma?

example 2
是的。謝謝你來接我們。
translates to
0: ['shìde']
1: ['。']
2: ['xièxiè']
3: ['nǐ']
4: ['láijiē']
5: ['wǒ']
6: ['mén']
7: ['。']

while correct is

Shìde. Xièxie nǐ lái jiē wǒmen

So I tried it with simplified chinese
是的。谢谢你来接我们。

0: ['shìde']
1: ['。']
2: ['xièxiènǐ']
3: ['lái']
4: ['jiē']
5: ['wǒmén']
6: ['。']

Am I doing something wrong or what is this funny thing that this project has so many stars while it is performing so bad?

Is translating Chinese to Pinyin properly so big of an issue?

Are there any AI Hanzi to Pinyin JavaScript translators pluggings that you could recommend me?

**Comment by hczhcz** [comment]
Chinese segmentation has no unique answer. For instance, all of them are valid:
* 谢谢/你/来/接/我们
* 谢谢你/来/接/我们
* 谢谢/你来/接/我们
* 谢谢/你/来/接/我/们

Neither does pinyin translation:
* 此人好(hǎo)说话 --- 好 = nice
* 此人好(hào)说话 --- 好 = like

> Is translating Chinese to Pinyin properly so big of an issue?

Yes.

> Am I doing something wrong?

As far as I know, the [builtin phrase dictionary](https://raw.githubusercontent.com/hotoo/pinyin/master/src/data/phrases-dict.ts) only covers Simplified Chinese.

**Comment by hotoo** [comment]
Thanks @hczhcz . yes, pinyin group is base on phrases, but segment is not easy to me.

**Comment by hotoo** [comment]
@JanVeb welcome.

**Comment by JanVeb** [comment]
Hi again @hotoo 
請問你是陳月美小姐嗎？ ['qing3 wen4', 'ni3', 'shi4', 'Chen2', 'yue4', 'Mei3', 'xiao3 jie5', 'ma5']
是的。謝謝你來接我們。 ['shi4 de5', 'xie4 xie5', 'ni3', 'lai2', 'jie1', 'wo3 men5']
歡迎你來臺灣！ ['huan1 ying2', 'ni3', 'lai2 Tai2', 'wan1']  -- notice lai2Tai2 is a word rather than Tai2wan1 --could fix this, just wanted to show it, where I get issue with segmentation approach, since this is only issue that I noticed till now

Basically, algorithm is always looking for longest possible word.

First it splits Chinese text into single characters, then joins first and second character and looks in dictionary, if there is a word in dictionary, if yes, then adds 3th character and checks if there is 3 character word, if yes, then ads 4th character to search word and checks if there is a word, and so on until there is no word.
When there is no word, then just delete last character and get words/word that it confirmed in previous step that it is there.

For example, if I check 3 character word, and there is none, then it deletes last character and looks for 2 character words, that it already before confirmed that they are there.

My presumption was that because there are thousands of Chinese characters there will not be often that random words will appear in text.

Though will need to do further tests, but I'm also busy building my project.

Also, I noticed that tones might be different from dictionary to dictionary, for example I use MGBD dictionary, some of its entries tones are different than in Taiwan university dictionary I also have, and also tones are different in some entries from HSK dictionary. My solution for this would be to add multiple dictionaries, and let user chose which dictionary he wants to use, based on he's needs, for example, if he is studying in some HSK program, he probably will want to use HSK dictionary. In cases where he enters characters that are not in HSK, then code would after confirming that there is no entire in HSK dictionary search MBDG dictionary as well.

If I seen correctly from your project, you are using segmentit library for segmenting Chinese?

If you would like to try my method of segmenting Chinese text to words, please let me know and Il provide you with code

Still, I didn't have chance to deal with issue, of characters/words which can have different pinyin, though I have idea how to approach that, would just need some data (I presume, even smaller data would suffice, as I presume, Chinese characters/words that can have different pinyin, are more frequently used, so it would be easier to get data points I need even from not so big texts)

Thank
