### ISSUE TITLE
四字词组的注音问题

### ISSUE THREAD

**Issue by hczhcz** [hotoo/pinyin#337]
```
> pinyin('流行', {segment:true})
[ [ 'liú' ], [ 'xíng' ] ]
> pinyin('音乐', {segment:true})
[ [ 'yīn' ], [ 'yuè' ] ]
> pinyin('流行音乐', {segment:true})
[ [ 'liú' ], [ 'háng' ], [ 'yīn' ], [ 'lè' ] ]
```

类似这种，由两个词语组成的词组。jieba 并不会把它们切开，但是合在一起在词典里找不到。

**Comment by hotoo** [comment]
"流行音乐" 被分词模块识别为一个完整的词组（而不是 "流行/音乐"），但是词库中只有 "流行歌曲"，而没有 "流行音乐"，所以被当作单字处理了。。。

临时解决方案是给分词库提交一个 "流行音乐" 的拼音库。

更希望有一个分词库，可以做到最小分词能力，这样对于拼音库来说更实用。

**Comment by hotoo** [comment]
fixed
