### ISSUE TITLE
打包的时候报错，alpha 版本

### ISSUE THREAD

**Issue by Vimalate** [hotoo/pinyin#344]
最近发现打包的时候会报错，

![image](https://user-images.githubusercontent.com/47288962/179468494-5aff32f3-ac49-4bff-965e-0af04bf83611.png)

**Comment by hotoo** [comment]
你的 webpack 配置不支持最新的 esm 写法：

```js
class foo {
  bar = 'hello';
  baz = 'world';

  constructor() {
    // ...
  }
}
```

**Comment by Lockseed** [comment]
> 你的 webpack 配置不支持最新的 esm 写法：
> 
> ```js
> class foo {
>   bar = 'hello';
>   baz = 'world';
> 
>   constructor() {
>     // ...
>   }
> }
> ```

遇到了同样的问题，请问这种情况应该升级或修改哪边的配置，是webpack还是babel？
类似这种用法，我在我自己的代码中使用就OK，但是如果第三方库中使用就会报错。
