### ISSUE TITLE
web版本的链接已经失效

### ISSUE THREAD

**Issue by zhaoleicpp** [hotoo/pinyin#348]
web版本的链接
https://github.com/hotoo/pinyin/tree/gh-pages/dist
已经失效

我用
tsc pinyin.ts --lib es2018 --target es2018
命令转化失败，因为需要nodejieba。

nodejieba是c的，实在不方便往网页上移植。

综上：跪求web版本的。

**Comment by leedom92** [comment]
@zhaoleicpp 你可以试一下这个链接
`https://github.com/hotoo/pinyin/tree/ddf628f397b03c405bddb1ce498f815561e7c39c/dist`
[点击跳转](https://github.com/hotoo/pinyin/tree/ddf628f397b03c405bddb1ce498f815561e7c39c/dist)

**Comment by zhaoleicpp** [comment]
万分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hotoo/pinyin] web版本的链接已经失效 (Issue #348)





 
@zhaoleicpp 你可以试一下这个链接
 https://github.com/hotoo/pinyin/tree/ddf628f397b03c405bddb1ce498f815561e7c39c/dist
 点击跳转

**Comment by KaelInvoker** [comment]
@leedom92 @zhaoleicpp 您好，请问上面给的链接web版要如何使用？
