### ISSUE TITLE
分词器nodejieba代码错误

### ISSUE THREAD

**Issue by LaoCheng-cjs** [hotoo/pinyin#351]
安装完成后和引入后，一启动项目就挂掉。

```
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'nodejieba'
Require stack:
```

> 经过两天折磨，反复设置 segment: "@node-rs/jieba",  反复安装 nodejieba 不同版本都无法安装。 travis-ci 发布出问题了，travis-ci 变成收费项目了

### 解决方案一：

1、看到源码中的：
在pinyin.js中，下面链接的文件
`
var segment_1 = require("./segment");
`

2、在 segment.js 文件中，下面这句话，有问题，一进来就必须执行，配置分词功能有点（呵呵）segment。也就是说安装nodejieba，看到下面的代码明白了
`
var nodejieba_1 = __importDefault(require("nodejieba"));
`

3、解决：将第2步手动改成
`
var nodejieba_1 = __importDefault(require("@node-rs/jieba"));
`

### 解决方案二：

1、通过此链接：https://github.com/yanyiwu/nodejieba/releases/ 找到相应操作系统文件，解压到 \node_modules 目录下，然后必须改名： nodejieba

**Comment by zhipenglin** [comment]
这个问题没人pr一下么，好蛋疼

**Comment by flyingCrp** [comment]
遇到相同问题

**Comment by hotoo** [comment]
nodejieba 是可选的，可以不用安装。
`npm i --no-optional`
