### ISSUE TITLE
有没有全局的segment设置？

### ISSUE THREAD

**Issue by JavaZWT** [hotoo/pinyin#357]
Hi，@hotoo

我的项目里使用pinyin 后，由于node版本较高，nodejieba 安装不成功，导致项目build阶段十分缓慢，现在想使用其他的 segment，但是我看demo里，都是需要在使用时指定 segment，如果使用时不设置，默认使用nodejieba，请问这个 segment 可以设置为全局的吗？ 设置后，默认后续默认就使用全局设置的 segment。

谢谢~

**Comment by hotoo** [comment]
现在不行，现在 pinyin() 就是一个函数，每次调用的时候传参数。

**Comment by JavaZWT** [comment]
看文档说明 segment 不传入默认情况下不是false吗？ 即不使用分词功能，项目中各个pinyin方法未对segment进行设置，为什么也会去尝试安装nodejieba呢？

**Comment by hotoo** [comment]
> 看文档说明 segment 不传入默认情况下不是false吗？ 即不使用分词功能，项目中各个pinyin方法未对segment进行设置，为什么也会去尝试安装nodejieba呢？
> 
> > 现在不行，现在 pinyin() 就是一个函数，每次调用的时候传参数。

1. 安装依赖时不知道运行时是否在使用。
2. 是可选依赖(optionalDependencies)，安装不成功也不影响使用。

**Comment by JavaZWT** [comment]
了解了，感谢~
