### ISSUE TITLE
安装3.0.0-alpha.5版本后运行，出现找不到模块`nodejieba`错误

### ISSUE THREAD

**Issue by chaselen** [hotoo/pinyin#359]
还没使用分词功能

```
node:internal/modules/cjs/loader:988
  throw err;
  ^
Error: Cannot find module '/var/www/wx/node_modules/.pnpm/nodejieba@2.5.2/node_modules/nodejieba/build/Release/nodejieba.node'
Require stack:
- /var/www/wx/node_modules/.pnpm/nodejieba@2.5.2/node_modules/nodejieba/index.js
- /var/www/wx/node_modules/.pnpm/pinyin@3.0.0-alpha.5/node_modules/pinyin/lib/segment.js
- /var/www/wx/node_modules/.pnpm/pinyin@3.0.0-alpha.5/node_modules/pinyin/lib/pinyin.js
- /var/www/wx/commands/index.ts
```

**Comment by tiannahaha** [comment]
> 还没使用分词功能
> 
> ```
> node:internal/modules/cjs/loader:988
>   throw err;
>   ^
> Error: Cannot find module '/var/www/wx/node_modules/.pnpm/nodejieba@2.5.2/node_modules/nodejieba/build/Release/nodejieba.node'
> Require stack:
> - /var/www/wx/node_modules/.pnpm/nodejieba@2.5.2/node_modules/nodejieba/index.js
> - /var/www/wx/node_modules/.pnpm/pinyin@3.0.0-alpha.5/node_modules/pinyin/lib/segment.js
> - /var/www/wx/node_modules/.pnpm/pinyin@3.0.0-alpha.5/node_modules/pinyin/lib/pinyin.js
> - /var/www/wx/commands/index.ts
> ```
I have the same problem

**Comment by portwatcher** [comment]
If you guys deploy your app through Docker, be sure to add `RUN apk add --no-cache --virtual .gyp python3 make g++` in your `Dockerfile`

**Comment by starcsb** [comment]
I meet the same issue. I choose to use [pinyin-pro](https://github.com/zh-lx/pinyin-pro), it doesn't have this issue. More important, it has higher accuracy, better performance and smaller size!

**Comment by youth7** [comment]
我也碰到相同的问题，看起来是安装nodejieba时候出错了
```
pnpm install pinyin
Packages: +79
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 293, reused 281, downloaded 0, added 0, done
node_modules/.pnpm/nodejieba@2.5.2/node_modules/nodejieba: Running install script, failed in 4.3s (skipped as optional)
```

**Comment by hotoo** [comment]
@chaselen @tiannahaha @youth7 试试 3.0.0-alpha.7

**Comment by youth7** [comment]
> I meet the same issue. I choose to use [pinyin-pro](https://github.com/zh-lx/pinyin-pro), it doesn't have this issue. More important, it has higher accuracy, better performance and smaller size!

最后采用[pinyin-pro](https://github.com/zh-lx/pinyin-pro)解决了问题，感谢
