### ISSUE TITLE
EsModule引用报错

### ISSUE THREAD

**Issue by ZMN8** [hotoo/pinyin#366]
![image](https://user-images.githubusercontent.com/20635903/236208509-012e06a1-491c-490b-b705-f562b9a1750d.png)

![image](https://user-images.githubusercontent.com/20635903/236208567-1bb230de-3dc7-45bb-8ca2-9a77e37f5dd1.png)

看npm包产物并没有 esm 的文件夹

**Comment by songwuk** [comment]
Using the `v2` version may be useful!

**Comment by starcsb** [comment]
试试 [pinyin-pro](https://github.com/zh-lx/pinyin-pro)，支持 esm、umd。并且有更好的性能、更高的转换准确率和更小的体积

**Comment by hotoo** [comment]
npm 上显示是有的 https://www.npmjs.com/package/pinyin?activeTab=code
