### ISSUE TITLE
vue2引入包后编译报错

### ISSUE THREAD

**Issue by Azheng168** [hotoo/pinyin#369]
![image](https://github.com/hotoo/pinyin/assets/60993656/3bac2125-5c91-4860-a3c0-60b64348bdeb)
![image](https://github.com/hotoo/pinyin/assets/60993656/27a85d9e-0dc7-4f38-a128-d73af1b51ea3)

以上是错误截图信息以及包package.json

**Comment by starcsb** [comment]
试试 [pinyin-pro](https://github.com/zh-lx/pinyin-pro)，有更好的性能、更高的转换准确率和更小的体积

**Comment by wjb120962** [comment]
我在vue.config.js中加入了这样的配置就好了
![image](https://github.com/hotoo/pinyin/assets/134665022/802021f9-f27f-4dc6-891c-d62db28f2d91)

**Comment by XiaoSongMAX** [comment]
你加到哪行代码是什么意思呀

**Comment by ma-dong-mei-2023** [comment]
> 我在vue.config.js中加入了这样的配置就好了 ![image](https://user-images.githubusercontent.com/134665022/241100337-802021f9-f27f-4dc6-891c-d62db28f2d91.png)
pinyin包里面用到了现代JavaScript，所以要用Babel转换一下

**Comment by jianmofeng** [comment]
<img width="515" alt="image" src="https://github.com/hotoo/pinyin/assets/23490892/05499008-24e0-4104-91de-a7b05e2534d4">
简单处理，用别名替换一下就好了
