### ISSUE TITLE
package.json is not node-pre-gyp ready:

### ISSUE THREAD

**Issue by caifu23** [hotoo/pinyin#370]
electron+vue，在主进程(node)使用import pinyin from "pinyin" 报错如下图： 
![pinyin](https://github.com/caifu23/test/blob/master/default%20(1).jpg?raw=true)

还有警告信息：
![warning](https://github.com/caifu23/test/blob/master/default%20(2).jpg?raw=true)

系统
linux 麒麟

版本
pinyin: 3.0.0-alpha.4
node: 16.5.0
electron: 15.4.0
vue: 2.6.11

**Comment by hotoo** [comment]
可选依赖，不使用分词不影响

**Comment by hotoo** [comment]
@caifu23  试试 3.0.0-alpha.7 版本。
