### ISSUE TITLE
《》和里面的内容被当成一个字符处理了

### ISSUE THREAD

**Issue by iooops** [hotoo/pinyin#372]
《水浒传》

=>
 
['《水浒传》']

**Comment by hotoo** [comment]
你用的什么版本？

```bash
$  pinyin 《水浒传》 
《 shuǐ hǔ chuán 》
```

![image](https://github.com/hotoo/pinyin/assets/143572/e561d5a8-784b-4512-976c-0a9c80d3b1f1)
