### ISSUE TITLE
添加{mode: 'normal'}无效

### ISSUE THREAD

**Issue by ccmtea** [hotoo/pinyin#374]
pinyin 版本：3.0.0-alpha.5
在web版，添加{mode: 'normal'}无效，打印出来始终是姓名模式

**Comment by hotoo** [comment]
请提供复现步骤

**Comment by ifunjoke** [comment]
> 请提供复现步骤

**pinyin@3.0.0-alpha.5**
```js
import pinyin from "pinyin";
pinyin(this.cityName,{mode:"NORMAL"})
```

![image](https://github.com/hotoo/pinyin/assets/2802035/b2d0889e-e307-42fe-abd7-f856f20b0016)

**Comment by hotoo** [comment]
@ifunjoke 这有什么问题？

**Comment by ifunjoke** [comment]
> pinyin 版本：3.0.0-alpha.5 在web版，添加{mode: 'normal'}无效，打印出来始终是姓名模式

兄弟，有个输出风格的参数加上即可。

```js
const py=await import(`https://cdn.jsdelivr.net/npm/pinyin@3.0.0-alpha.5/+esm`)
console.log(py.pinyin("测试",{style:'NORMAL',mode:"NORMAL",segment:false,group:false}).join(' '));
```
