### ISSUE TITLE
吕姓pinyin怎么处理成LYU

### ISSUE THREAD

**Issue by cfop0608** [hotoo/pinyin#375]
吕姓pinyin怎么处理成LYU

**Comment by ifunjoke** [comment]
```js
const py = await import(`https://cdn.jsdelivr.net/npm/pinyin@3.0.0-alpha.5/+esm`);
let surname = "吕一";
console.log(py.pinyin(surname, {
		style: 'NORMAL',
		mode: "NORMAL",
		segment: false,
		group: false
	})
	.map((v, i) => {
		console.log(v, i, surname[i]);
		return v ? . [0] === 'lv' && surname[i] === '吕' ? 'LYU' : v
	})
	.join(' '));
```
# result
console print `LYU yi`

**Comment by hotoo** [comment]
- [公安部：新版护照吕姓改拼“LYU”](https://china.huanqiu.com/article/9CaKrnJxk0l)
- [科普 | “吕”（Lǚ）姓的大写究竟是 LYU、LV，还是 LU？_拼音_字母_问题](https://www.sohu.com/a/562678582_121124287)
- [科普 | “吕”（Lǚ）姓的大写究竟是 LYU、LV，还是 LU？_拼音_字母_问题](https://www.sohu.com/a/562678582_121124287)
