### ISSUE TITLE
希望style可以多选

### ISSUE THREAD

**Issue by wangyupo** [hotoo/pinyin#378]
希望可以多选，比如我搜“弹窗”，我希望tanchuang可以搜出来，也希望tc可以搜出来。这是我现在的[处理方式](https://github.com/wangyupo/v3s/blob/5b9242701046a2fbfaa7c917fbe45775f4be077f/src/layout/components/MenuFilter/DialogFilter.vue#L118)。

**Comment by hotoo** [comment]
1. 你现在的方法也是很正常的方式。只是要计算 2 次，如果性能没有大问题这样是OK的。
2. 以 pinyin 现有的类型定义，无法再扩展出其他的返回结果。不过可以考虑将 format.js 中的 toFixed 函数导出，你只需要调用一次 pinyin，然后用 toFixed 来生成其他风格。
3. 欢迎你来个 PR 吧。
