### ISSUE TITLE
npm上的版本问题

### ISSUE THREAD

**Issue by YolineWu** [hotoo/pinyin#387]
npm上的版本搞得有点懵，5个月前发布3.1.0，4个月前又发布了4.0.0-alpha.0，现在npm上的默认安装版本是4.0.0-alpha.0，这个版本能用吗？我之前用的是^2.11.2，后面发布的3.0和4.0有什么变化？兼容^2.11.2吗？现在是安装3.1.0还是4.0.0-alpha.0？

**Comment by M69W** [comment]
在 `package.json ` 提示是 `Latest version: 4.0.0-alpha.0 published 5 months ago`
目前用 2.11.2
[releases](https://github.com/hotoo/pinyin/releases) 现在是 2.11.0
[tags](https://github.com/hotoo/pinyin/tags) 现在是 2.11.2

**Comment by hotoo** [comment]
各个版本基本是兼容的，主要是算法层面的升级
