### ISSUE TITLE
包的入口文件不存在

### ISSUE THREAD

**Issue by HandsomeTea** [hotoo/pinyin#390]
nodejs 20.11.1，typescript ^5.4.5
后端安装，项目启动报错
Cannot find module 'xxx/node_modules/pinyin/dist/pinyin.js'. Please verify that the package.json has a valid "main" entry

pinyin这个包的package.json的main属性写的包的入口文件找不到

**Comment by tangshanghai** [comment]
这个包都没有构建，下载次数那么多，都没人提出疑问么

**Comment by EVANYXW** [comment]
遇到同样问题

**Comment by hotoo** [comment]
@HandsomeTea @EVANYXW @tangshanghai fixed
