### ISSUE TITLE
Next.JS: Module not found: Can't resolve 'pinyin'

### ISSUE THREAD

**Issue by stevexyh** [hotoo/pinyin#393]
- Related: #386 
![image](https://github.com/hotoo/pinyin/assets/33098678/2d128a1c-9d37-4633-ba35-0469820b298f)

Tried installing `@types/pinyin`, but still doesn't work

```
        "next": "^14.2.4",
        "pinyin": "^4.0.0-alpha.0",
        "@types/pinyin": "^2.10.2",
```

**Comment by M69W** [comment]
试试 "pinyin": "^2.11.2",
alpha 版本你确定敢放生产？

**Comment by hotoo** [comment]
@stevexyh fixed
