### ISSUE TITLE
疑似内存泄露？

### ISSUE THREAD

**Issue by rojer95** [hotoo/pinyin#394]
最近一个项目接入了pinyin这个库，提供了一个接口给前端调用，框架是基于nestjs的
接入后这个项目过一段时间就会OOM，后来把pinyin这个库去掉了，就正常了
也不知道是不是我使用的方法有问题
## 整体内存占用走势
![image](https://github.com/hotoo/pinyin/assets/20662049/ff755cfc-25b2-4baf-ab7b-ad2ab7ae71a0)

### 刚刚启动
![image](https://github.com/hotoo/pinyin/assets/20662049/b68e9169-0d8a-4b21-9b73-7550e5248104)
### 运行一段时间
![image](https://github.com/hotoo/pinyin/assets/20662049/b882047c-ce47-410c-afe6-9d5e79cbed01)

### 刚刚启动
![image](https://github.com/hotoo/pinyin/assets/20662049/eeb45639-4b9c-4e7a-9857-9899e320897a)
### 运行一段时间
![image](https://github.com/hotoo/pinyin/assets/20662049/debfae70-b486-4a9e-97f1-5f593f8ed6ce)

相关代码
```tsx
@Controller('/dict')
export class DictController {

  @Post('/pinyin')
  async getPinyin(@Body('str') str: string) {
    return { pinyin: getPinyin(str) };
  }
}
```

```tsx
import { uniq } from 'lodash';
import pinyin from 'pinyin';

const replaceNumber = (i: string) => {
  let temp: string = i;
  const numbers = {
    1: '一',
    2: '二',
    3: '三',
    4: '四',
    5: '五',
    6: '六',
    7: '七',
    8: '八',
    9: '九',
  };

  Object.keys(numbers).map((number) => {
    temp = temp.replace(new RegExp(String(number), 'g'), numbers[number]);
  });

  return temp;
};

export const getPinyin = (str) => {
  try {
    let str1 = replaceNumber(str);
    if (str1 !== str) str1 = `${str} ${str1}`;
    const py = pinyin(str1, {
      heteronym: true,
      style: 'first_letter',
      compact: true,
      segment: true,
    });
    return uniq(
      py
        .map((i) => i.join(''))
        .join(' ')
        .toLowerCase()
        .split(/\s/)
        .filter((i) => !!i),
    ).join(' ');
  } catch (error) {
    return '';
  }
};
```

**Comment by hotoo** [comment]
@rojer95 把 new RegExp 去掉，或者固化正则表达式不要每次 new。
