### ISSUE TITLE
upgrade nodejieba@1.2.2

### ISSUE THREAD

**Issue by fundon** [hotoo/pinyin#49]
ping @hotoo  https://github.com/yanyiwu/nodejieba/commit/94b07d3ebb2ad8782b83a11e6fe7c8c049d90bd8

**Comment by lovell** [comment]
Ni Hao. I think this upgrade is necessary for the `keystone > keystone-utils > limax > pinyin > nodejieba` dependency chain - see also https://github.com/lovell/limax/issues/7 

I'm happy to submit a PR and/or help test this.

**Comment by lovell** [comment]
Xie xie ni bang wo.

**Comment by fundon** [comment]
@lovell haha，google translate?

**Comment by hotoo** [comment]
Bu ke qi (You're welcome) :)
