### ISSUE TITLE
装Pinyin库 WebStrom 10会一直Indexing 别的包都没事儿

### ISSUE THREAD

**Issue by freew01f** [hotoo/pinyin#52]
这个是怎么回事儿

**Comment by hotoo** [comment]
不用 WebStrom 抱歉不能回答。可能是拼音库比较大的缘故，详细请咨询 WebStrom 客服，谢谢 ：）

**Comment by Tedko** [comment]
数据最好命名成 .json 不然 ide 会 indexing

**Comment by hotoo** [comment]
- 抱歉，最大的数据部分（data/dict-zi.js）不好改成 json：

  ![2016-01-21 11 12 51](https://cloud.githubusercontent.com/assets/143572/12470551/27a4b5d8-c030-11e5-8cf7-2eebf6864666.png)

- 请看看 IDE 是否可以忽略 node_modules 目录。
- 将来数据部分可能会改成二进制形式。

非常抱歉。

**Comment by freew01f** [comment]
感谢~
