### ISSUE TITLE
支持Bower发布

### ISSUE THREAD

**Issue by lygstate** [hotoo/pinyin#69]
安装spm实在太慢，依赖太重

**Comment by hotoo** [comment]
推荐使用 npm/cnpm

**Comment by lygstate** [comment]
@hotoo 还有其它问题，就是spm  安装包太大，竟然还依赖于 phantomjs

**Comment by hotoo** [comment]
用 npm/cnpm

**Comment by hotoo** [comment]
@lygstate 我不用 Bower，所以如果你需要的话，请提交 PR 吧。
