### ISSUE TITLE
是否尝试使用Redis或Mongodb?

### ISSUE THREAD

**Issue by futurist** [hotoo/pinyin#70]
测试了下虽然性能不错，但对于经常要查询拼音的应用，最好还是后端有个DB异步查询。是否可以加入Redis或Mongodb做为字典存储的功能？

**Comment by hotoo** [comment]
需求是什么？

**Comment by futurist** [comment]
是的，如果打开segment，分词会阻塞node。就算不开，并发大时阻塞的问题也会比较明显

**Comment by hotoo** [comment]
现在的算法主要还是 CPU 密集型的，异步没意义。
改成数据库查询的 IO 密集型的话，数据库的查询同样耗性能。
另外其实现在的字典就是一个内存级别的 Key/Value 数据库。

**Comment by futurist** [comment]
只是个建议. 知道有这么回事吧, 具体是不是需要, 还要多测试，目前的方式用着也没大问题。
