### ISSUE TITLE
github page被打包到npm里 -> _site目录

### ISSUE THREAD

**Issue by phodal** [hotoo/pinyin#73]
total 88
	drwxr-xr-x  17 fdhuang  staff   578B Nov 19 13:36 .
	drwxr-xr-x   4 fdhuang  staff   136B Nov 19 13:36 ..
	-rw-r--r--   1 fdhuang  staff   5.0K Aug 23 08:29 .eslintrc
	-rw-r--r--   1 fdhuang  staff    56B Oct 22  2014 .npmignore
	-rw-r--r--   1 fdhuang  staff   2.4K Aug 25 09:33 CHANGELOG.md
	-rw-r--r--   1 fdhuang  staff   1.9K Aug 25 09:36 Makefile
	-rw-r--r--   1 fdhuang  staff   4.4K Aug  4 08:42 README-us_EN.md
	-rw-r--r--   1 fdhuang  staff   5.0K Aug  4 08:42 README.md
	drwxr-xr-x  17 fdhuang  staff   578B Nov 19 13:35 _site
	drwxr-xr-x   3 fdhuang  staff   102B Aug 24 10:12 bin
	drwxr-xr-x   6 fdhuang  staff   204B Nov 19 13:35 coverage
	drwxr-xr-x   3 fdhuang  staff   102B Jun  9 07:44 dist
	drwxr-xr-x   3 fdhuang  staff   102B Aug 24 10:12 examples
	-rw-r--r--   1 fdhuang  staff    43B Aug 24 10:12 index.js
	drwxr-xr-x   4 fdhuang  staff   136B Nov 19 13:36 node_modules
	-rw-r--r--   1 fdhuang  staff   1.9K Nov 19 13:36 package.json
	drwxr-xr-x   9 fdhuang  staff   306B Nov 19 13:36 src

**Comment by hotoo** [comment]
感谢 ：）
