### ISSUE TITLE
pinyin.js中多余的逗号在ie8下报错：‘缺少标识符、字符串或数字’

### ISSUE THREAD

**Issue by WwupengP** [hotoo/pinyin#75]
在src/pinyin.js中，

    var PINYIN_STYLE = {
        NORMAL: 0,  // 普通风格，不带音标。
        TONE: 1,    // 标准风格，音标在韵母的第一个字母上。
        TONE2: 2,   // 声调中拼音之后，使用数字 1~4 标识。
        INITIALS: 3,// 仅需要声母部分。
        FIRST_LETTER: 4, // 仅保留首字母。
    };

倒数第二行的行尾多了个‘,’，在ie8下会报错

**Comment by WwupengP** [comment]
还有一处：

    var DEFAULT_OPTIONS = {
        style: PINYIN_STYLE.TONE, // 风格
        segment: false, // 分词。
        heteronym: false, // 多音字
    };

**Comment by WwupengP** [comment]
路径错误了 在`lib/pinyin.js`中

**Comment by hotoo** [comment]
你贴的是编译后的代码？你可以找编译工具解决掉。

**Comment by WwupengP** [comment]
https://github.com/hotoo/pinyin/blob/master/lib/pinyin.js

**Comment by hotoo** [comment]
源文件是 ES6 语法，支持尾逗号。

你要用编译工具处理下。

**Comment by WwupengP** [comment]
多谢
