### ISSUE TITLE
在web中使用时，phonetic-symbol.js和dict-zi-web.js存在问题

### ISSUE THREAD

**Issue by hxgqh** [hotoo/pinyin#77]
我们使用的开发框架是：Grunt + Angular + RequireJS。
这两个文件在Web端会抛出错误：module is not defined。
需要按如下方式解决：

    define(function (require, exports, module) {
        module.exports = {
            ....
        }
    })

**Comment by hotoo** [comment]
可能你的打包工具问题。pinyin 模块使用的是 CommonJS 规范，不需要 define 包装（CMD 规范）。

你可以使用 webpack + babel，或者 spm 打包。
