### ISSUE TITLE
web版

### ISSUE THREAD

**Issue by chen4342024** [hotoo/pinyin#85]
请问在web版我该如何使用？我相关的文档说明吗？

**Comment by qiaoyahao** [comment]
同问 ！我怎么找不到WEB版啊？

**Comment by zileyuan** [comment]
再同问 ！我怎么找不到WEB版啊？

**Comment by hotoo** [comment]
- 如果你用 CommonJS，require('pinyin') 然后使用打包工具打包即可。
- 你还可以看看这个 https://github.com/hotoo/pinyin/tree/gh-pages/dist/pinyin
