### ISSUE TITLE
希望能增加驼峰大小写

### ISSUE THREAD

**Issue by intijk** [hotoo/pinyin#88]
如题，这种风格也蛮需要的，第一个字母大写，其它字母小写。

**Comment by hotoo** [comment]
这种很不常见吧？你先自己转吧，以后看需求强烈再加。

**Comment by intijk** [comment]
额，其实我fork了一下你的，已经实现好了，test也写了，你需要的话我可以发pull request 给你。

intijk@Bumblebee: bin $ ./pinyin "中文 中国(china)"
zhōng wén   zhōng guó (china)
intijk@Bumblebee: bin $ ./pinyin -s camel "中文 中国(china)"
Zhong Wen   Zhong Guo (china)

**Comment by hotoo** [comment]
既然这样，你先提 PR 看看吧。

另外，你的什么场景使用这种风格？

**Comment by intijk** [comment]
是这样的，我有一堆文件，是中文的文件名，但是一些特定场合不能使用中文作为文件名，文件系统不支持。所以我想把他转换成英文的，比如

    小精灵.txt

转成

    XiaoJingLing.txt

我看到源码里面直接用 .join(" ") 返回结果了，我还希望能够增加一个选项打掉这个空格，我可以尝试写一下。

**Comment by intijk** [comment]
最好是能指定一个分隔符

**Comment by hotoo** [comment]
### 关于分隔符

这个模块提供的命令行工具是不支持指定分隔符的。不过我想你的这个场景应该是使用的 API 而不是命令行方式。

使用 API 方式，返回的是数组，你可以按需设置分隔符。 http://w3school.com.cn/jsref/jsref_join.asp

**命令行可以考虑增加分隔符的功能。**

### 关于驼峰风格

我暂时还没想清楚是否要合并 #89 这个 PR，因为：

1. 不确定这个风格是否常用（如果你可以提供其他使用这个风格的场景就更好了）。
2. 不排除还有些人希望使用全部大写，或者其他特殊的风格的情况，都加到这个模块不合适。
3. 开发者可以很轻松的自行转换。

    ```js
    pinyin('小精灵').map(pys => {
      return pys.map(py => {
        return py.charAt(0).toUpperCase() + py.slice(1);
        // return py.toUpperCase();
        // return whatever;
      });
    });
    ```

这个功能我想先晾晾，**不过还是请你先把代码风格改下以便通过 eslint 校验。**

**Comment by intijk** [comment]
恩，可以的，你可以考虑考虑。
严格的驼峰不能有空格的，你说的没错，我可以把名字改成类似 FIRST_CAPITAL 之类的。

我去看看分隔符和eslint

**Comment by zhuangya** [comment]
https://doclets.io/dleitee/strman/master#dl-toCamelCase

可以用这个来直接自己转呀

我觉得可以关掉这个了……

**Comment by hotoo** [comment]
先关了。
